# Site Settings
title:               Joalon
tagline:             a software engineer
description:
baseurl:            #"/Lagrange"
url:                "https://joalon.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Joakim LÃ¶nnegren"
  email:             "joakim.lonnegren@gmail.com"
  twitter:           "LonnegrenJoakim"
  github:            "joalon"
  linkedin:          "joakimlonnegren"
navigation:
- title: About
  url: /about

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
encoding:            UTF-8
